version: '3'
services:
   frontend:
     build:
      context: .
      dockerfile: .development.dockerfile
     ports:
      - '3000:3000'
     volumes:
       - '.:/usr/src/app'
     container_name: fuse-react-boilerplate
